# tools/compilers/compiler_glyph.py

from __future__ import annotations
from pathlib import Path

from tools.loaders.load_mji_00602_xlsx import load_mji_00602_xlsx
from tools.loaders.load_mjih_00201_xlsx import load_mjih_00201_xlsx
from tools.core.model import GlyphRecord


# ------------------------------------------------------------
# name の重複チェック
# ------------------------------------------------------------

def ensure_unique_names(records: list[GlyphRecord]):
    seen = set()
    duplicates = []

    for rec in records:
        if rec.name in seen:
            duplicates.append(rec.name)
        else:
            seen.add(rec.name)

    if duplicates:
        raise ValueError(f"Duplicate glyph names detected: {duplicates}")


# ------------------------------------------------------------
# glyph_table.py の書き出し
# ------------------------------------------------------------

def write_glyph_table_py(records: list[GlyphRecord], out_path: Path, descriptions: list[str], sort: bool = False):
    lines = []

    lines.append("# -*- coding: utf-8 -*-")
    lines.append("# Auto-generated by compiler_glyph.py")
    lines.append("# NOTE: This file contains Japanese characters in comments.")
    lines.append("#       All content is encoded in UTF-8 (without BOM).")
    for desc in descriptions:
        lines.append(f"# {desc}")
    
    lines.append("")

    lines.append("glyph_table = {")

    # sortが真の場合、name でソート
    for rec in sorted(records, key=lambda r: r.name) if sort else records:
        lines.append(f"    {rec.name!r}: {{")
        lines.append(f"        # {rec.comment}")
        lines.append(f"        'b': {rec.b!r},")
        lines.append(f"        'v': {rec.v!r},")
        lines.append(f"        'active': {rec.active!r},")
        lines.append("    },")
    lines.append("}")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")


# ------------------------------------------------------------
# MJ（漢字）＋ MJIH（変体仮名）を合成して glyph_table を生成
# ------------------------------------------------------------

def compile_glyph_table_mj(out_path: Path):
    base = Path(__file__).resolve().parent.parent

    descriptions = [
        "",
        "set: mj",
        "",
        "file 1: mji.00602.xlsx",
        "file 2: MJIH00201.xlsx",
        "",
        # --- IPA 出典情報を追加 ---
        "-----------------------------------------------------------------------------",
        "本データは、IPA（独立行政法人 情報処理推進機構）が公開する「MJ文字情報一覧表」および",
        "「MJ文字情報一覧表 変体仮名編」の XLSX ファイルを基に生成されている。",
        "",
        "これらの XLSX ファイルは IPA の著作物であり、次の公式サイトから取得した：",
        "",
        "    https://moji.or.jp/mojikiban/mjlist/",
        "",
        "本データは、当該 XLSX の内容を解析し、変体仮名を含めたMJ文字情報の統合テーブルとして",
        "Python モジュール形式で再構成したものである。",
        "-----------------------------------------------------------------------------",
    ]

    # --- MJ（漢字編） ---
    xlsx_mj = base / "data" / "mji.00602.xlsx"
    print(f"[compiler] Loading MJ Kanji: {xlsx_mj}")
    records_mj = load_mji_00602_xlsx(xlsx_mj)
    print(f"[compiler] Loaded MJ Kanji: {len(records_mj)} records")

    # --- MJIH（変体仮名編） ---
    xlsx_mjih = base / "data" / "MJIH00201.xlsx"
    print(f"[compiler] Loading MJ Hentaigana: {xlsx_mjih}")
    records_mjih = load_mjih_00201_xlsx(xlsx_mjih)
    print(f"[compiler] Loaded MJ Hentaigana: {len(records_mjih)} records")

    # --- 合成（list のまま） ---
    records = records_mj + records_mjih
    print(f"[compiler] Total records (before duplicate check): {len(records)}")

    # --- name の重複チェック ---
    ensure_unique_names(records)
    print("[compiler] Name uniqueness check passed")

    write_glyph_table_py(records, out_path, descriptions)
    print(f"[compiler] Wrote: {out_path.resolve()}")


# ------------------------------------------------------------
# main
# ------------------------------------------------------------

def main():
    base = Path(__file__).resolve().parent.parent.parent
    out_path = Path(base / "mjrengo_data_mj" / "src/mjrengo/data" / "mj" / "data_mj.py")
    compile_glyph_table_mj(out_path)


if __name__ == "__main__":
    main()
