# tools/compiler_glyph.py

from pathlib import Path
import argparse

from tools.loaders.load_mji_00602_xlsx import load_mji_00602_xlsx
from tools.core.model import GlyphRecord


def record_to_dict(rec: GlyphRecord) -> dict:
    return {
        "name": rec.name,
        "b": rec.b,
        "v": rec.v,
        "active": rec.active,
        "comment": rec.comment,
    }


def write_glyph_table_py(records: dict[str, GlyphRecord], out_path: Path, description: list):
    lines = []

    lines.append("# -*- coding: utf-8 -*-")
    lines.append("# Auto-generated by compiler_glyph.py")
    lines.append("# NOTE: This file contains Japanese characters in comments.")
    lines.append("#       All content is encoded in UTF-8 (without BOM).")
    lines.append("")

    for desc in description:
        lines.append(f"# {desc}")
    lines.append("")
    
    lines.append("glyph_table = {")

    for name, rec in sorted(records.items()):
        d = record_to_dict(rec)
        lines.append(f"    {name!r}: {{ # {d['comment']}")
        lines.append(f"        'b': {d['b']!r},")
        lines.append(f"        'v': {d['v']!r},")
        lines.append(f"        'active': {d['active']!r},")
        lines.append("    },")
    lines.append("}")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")


def compile_glyph_table_mj(out_path: Path):
    base = Path(__file__).resolve().parent.parent
    xlsx_path = base / "data" / "mji.00602.xlsx"

    print(f"[compiler] Loading: {xlsx_path}")
    records = load_mji_00602_xlsx(xlsx_path)
    print(f"[compiler] Loaded {len(records)} records")

    write_glyph_table_py(records, out_path, ["set: mj", "source file: mji.00602.xlsx"])
    print(f"[compiler] Wrote: {out_path.resolve()}")


def main():
    base = Path(__file__).resolve().parent.parent.parent    # "/home/vscode/dev/code"
    # set: mj
    out_path = Path(base / "mjrengo_data_mj" / "src/mjrengo/data" / "mj" / "data_mj.py")
    compile_glyph_table_mj(out_path)


if __name__ == "__main__":
    main()
