# code/pyproject.toml

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "../__about__.py"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/mjrengo"]


[project]
name = "mjrengo_replace"
dynamic = ["version"]
# dependencies = [
#   "unoserver",
#   "docxtpl",
#   "python_odt_template[standard] @ git+https://github.com/jp-one/python-odt-template-forked.git",
#   "relatorio[chart,fodt] @ git+https://github.com/jp-one/relatorio-forked.git",
# ]
requires-python = ">=3.8"
authors = [{ name = "jp-one" }]
description = "Unicode UCS/IVS utilities for MJ/GJ glyph processing"
readme = "README.md"
license = "MIT"
license-files = ["LICEN[CS]E*"]
keywords = [
  # "report-engine",
  # "unoserver",
  # "python-odt-template",
  # "python-docx-template",
  # "jinja2",
]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/jp-one/mjrengo"
Repository = "https://github.com/jp-one/mjrengo"
